name: DB Schema Deploy

on:
  push:
    branches: [master]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Call MnM
        run: |
          curl -X POST http://95.216.209.142:3000/deploy \
               -H "Content-Type: application/json" \
               -d '{"sha":"${{ github.sha }}"}'